"""change dept 

Revision ID: 24da168da9c3
Revises: 2232009e0ad6
Create Date: 2024-06-26 15:27:33.306152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24da168da9c3'
down_revision = '2232009e0ad6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   
    
  op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   op.rename_table('departments', 'department')
    # ### end Alembic commands ###
